# Generated by Django 2.2 on 2019-05-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BisikletModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_id', models.CharField(blank=True, editable=False, max_length=255)),
                ('u_id', models.CharField(max_length=255)),
                ('istasyon', models.CharField(max_length=255)),
                ('arizali', models.BooleanField(default=False)),
                ('son_alan', models.CharField(blank=True, default='00000000000', max_length=8)),
                ('giris_tarih', models.CharField(blank=True, editable=False, max_length=255)),
                ('istasyonda', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EtkinlikModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_id', models.CharField(blank=True, editable=False, max_length=255)),
                ('ogrenci_no', models.CharField(max_length=12)),
                ('bisiklet_id', models.CharField(max_length=8)),
                ('alinanTarih', models.CharField(max_length=255)),
                ('verilenTarih', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='IstasyonModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255)),
                ('adres', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OgrenciModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('okul_no', models.CharField(max_length=12)),
                ('ad', models.CharField(max_length=255)),
                ('soyad', models.CharField(max_length=255)),
                ('rfid', models.CharField(max_length=255)),
                ('ceza', models.CharField(default='0', max_length=3)),
                ('yasakli', models.BooleanField(default=False)),
                ('bisikletiVar', models.BooleanField(default=False)),
                ('son_etkinlik', models.CharField(default='00000000', max_length=8)),
            ],
        ),
    ]
