# Generated by Django 2.2 on 2019-05-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etkinlikmodel',
            name='alinanTarih',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='etkinlikmodel',
            name='verilenTarih',
            field=models.CharField(default='-', max_length=255),
        ),
    ]
